version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
